name: PHP + MySQL + phpMyAdmin Setup

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: mydb
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, mysqli, pdo_mysql
          coverage: none

      - name: Install Composer dependencies if composer.json exists
        run: |
          if [ -f "composer.json" ]; then
            composer install --no-progress --prefer-dist
          else
            echo "No composer.json found, skipping Composer install."
          fi

      - name: Download phpMyAdmin
        run: |
          wget https://files.phpmyadmin.net/phpMyAdmin/5.2.2/phpMyAdmin-5.2.2-all-languages.zip
          unzip phpMyAdmin-5.2.2-all-languages.zip

      - name: Setup phpMyAdmin folder
        run: |
          mkdir -p phpmyadmin
          mv phpMyAdmin-5.2.2-all-languages/* phpmyadmin/
          ls -la phpmyadmin
