name: PHP + MySQL + phpMyAdmin Setup

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: mydb
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Setup PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, mysqli, pdo_mysql
          coverage: none

      # 3️⃣ Install Composer dependencies (only if composer.json exists)
      - name: Install Composer dependencies
        if: ${{ exists('composer.json') }}
        run: composer install --no-progress --prefer-dist

      # 4️⃣ Download and extract phpMyAdmin
      - name: Download phpMyAdmin
        run: |
          wget https://files.phpmyadmin.net/phpMyAdmin/5.2.2/phpMyAdmin-5.2.2-all-languages.zip
          unzip phpMyAdmin-5.2.2-all-languages.zip

      # 5️⃣ Create phpmyadmin folder and move files
      - name: Setup phpMyAdmin folder
        run: |
          mkdir -p phpmyadmin
          mv phpMyAdmin-5.2.2-all-languages/* phpmyadmin/
          ls -la phpmyadmin
